AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  BotFromBar

  Sample SAM Template for BotFromBar

Parameters:
  ZKToken:
    Type: String
    Description: OAuth Token the bot needs to talk
  WfbToken:
    Type: String
    Description: OAuth Token the bot needs to talk
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  BloopsBot:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: bloopsbot/
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          TOKEN: !Ref WfbToken
      Events:
        Wfb:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /wfb
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BloopsPoints

  BloopsPoints:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: subject
          AttributeType: S
        - AttributeName: teamId
          AttributeType: S
      KeySchema:
        - AttributeName: subject
          KeyType: HASH
        - AttributeName: teamId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      TableName: BloopsPoints

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  WfbApi:
    Description: "API Gateway endpoint URL for Prod stage for BloopsBot"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/wfb/"
  WfbFunction:
    Description: "BloopsBot Lambda Function ARN"
    Value: !GetAtt BloopsBot.Arn
  WfbIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt BloopsBotRole.Arn
